---
- name: Directory to store iavf driver
  file:
    path: "{{ iavf_dest }}"
    state: directory

- name: Fetch iavf driver
  get_url:
    url: "{{ iavf_url }}"
    dest: "{{ iavf_dest }}/{{ iavf_gzfile }}"
    validate_certs: False
    checksum: "{{ iavf_checksum[iavf_version] }}"
  register: package_result
  until: package_result is succeeded
  retries: 10
  delay: 5

- name: Unarchive the iavf file
  unarchive:
    src: "{{ iavf_dest }}/{{ iavf_gzfile }}"
    dest: "{{ iavf_dest }}"
    copy: no

- name: Cleanup the archive to save space
  file:
      path: "{{ iavf_dest }}/{{ iavf_gzfile }}"
      state: absent
